/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as RequestARideRouteImport } from './routes/request-a-ride'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as JoinOurNetworkRouteImport } from './routes/join-our-network'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas.index'
import { Route as StaffLoginRouteImport } from './routes/staff.login'
import { Route as ServiceAreasCityRouteImport } from './routes/service-areas.$city'
import { Route as ProviderLoginRouteImport } from './routes/provider.login'
import { Route as PatientLoginRouteImport } from './routes/patient.login'
import { Route as FacilityLoginRouteImport } from './routes/facility.login'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as AuthenticatedRequestsIndexRouteImport } from './routes/_authenticated/requests.index'
import { Route as AuthenticatedRequestsIdRouteImport } from './routes/_authenticated/requests.$id'
import { Route as AuthenticatedProviderMedicaidRouteImport } from './routes/_authenticated/provider.medicaid'
import { Route as AuthenticatedProviderDashboardRouteImport } from './routes/_authenticated/provider.dashboard'
import { Route as AuthenticatedPatientDashboardRouteImport } from './routes/_authenticated/patient.dashboard'
import { Route as AuthenticatedFacilityDashboardRouteImport } from './routes/_authenticated/facility.dashboard'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicIntegrationsRoutegenieWebhookRouteImport } from './routes/api/public/integrations/routegenie.webhook'
import { Route as ApiPublicIntegrationsHibambiWebhookRouteImport } from './routes/api/public/integrations/hibambi.webhook'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestARideRoute = RequestARideRouteImport.update({
  id: '/request-a-ride',
  path: '/request-a-ride',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinOurNetworkRoute = JoinOurNetworkRouteImport.update({
  id: '/join-our-network',
  path: '/join-our-network',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const StaffLoginRoute = StaffLoginRouteImport.update({
  id: '/staff/login',
  path: '/staff/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasCityRoute = ServiceAreasCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const ProviderLoginRoute = ProviderLoginRouteImport.update({
  id: '/provider/login',
  path: '/provider/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientLoginRoute = PatientLoginRouteImport.update({
  id: '/patient/login',
  path: '/patient/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilityLoginRoute = FacilityLoginRouteImport.update({
  id: '/facility/login',
  path: '/facility/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRequestsIndexRoute =
  AuthenticatedRequestsIndexRouteImport.update({
    id: '/requests/',
    path: '/requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRequestsIdRoute = AuthenticatedRequestsIdRouteImport.update({
  id: '/requests/$id',
  path: '/requests/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProviderMedicaidRoute =
  AuthenticatedProviderMedicaidRouteImport.update({
    id: '/provider/medicaid',
    path: '/provider/medicaid',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProviderDashboardRoute =
  AuthenticatedProviderDashboardRouteImport.update({
    id: '/provider/dashboard',
    path: '/provider/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPatientDashboardRoute =
  AuthenticatedPatientDashboardRouteImport.update({
    id: '/patient/dashboard',
    path: '/patient/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacilityDashboardRoute =
  AuthenticatedFacilityDashboardRouteImport.update({
    id: '/facility/dashboard',
    path: '/facility/dashboard',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsRoutegenieWebhookRoute =
  ApiPublicIntegrationsRoutegenieWebhookRouteImport.update({
    id: '/api/public/integrations/routegenie/webhook',
    path: '/api/public/integrations/routegenie/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsHibambiWebhookRoute =
  ApiPublicIntegrationsHibambiWebhookRouteImport.update({
    id: '/api/public/integrations/hibambi/webhook',
    path: '/api/public/integrations/hibambi/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join-our-network': typeof JoinOurNetworkRoute
  '/mcp': typeof McpRoute
  '/membership': typeof MembershipRoute
  '/providers': typeof ProvidersRoute
  '/request-a-ride': typeof RequestARideRoute
  '/resources': typeof ResourcesRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/facility/login': typeof FacilityLoginRoute
  '/patient/login': typeof PatientLoginRoute
  '/provider/login': typeof ProviderLoginRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/staff/login': typeof StaffLoginRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/facility/dashboard': typeof AuthenticatedFacilityDashboardRoute
  '/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
  '/provider/dashboard': typeof AuthenticatedProviderDashboardRoute
  '/provider/medicaid': typeof AuthenticatedProviderMedicaidRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/requests/': typeof AuthenticatedRequestsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/integrations/hibambi/webhook': typeof ApiPublicIntegrationsHibambiWebhookRoute
  '/api/public/integrations/routegenie/webhook': typeof ApiPublicIntegrationsRoutegenieWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join-our-network': typeof JoinOurNetworkRoute
  '/mcp': typeof McpRoute
  '/membership': typeof MembershipRoute
  '/providers': typeof ProvidersRoute
  '/request-a-ride': typeof RequestARideRoute
  '/resources': typeof ResourcesRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/facility/login': typeof FacilityLoginRoute
  '/patient/login': typeof PatientLoginRoute
  '/provider/login': typeof ProviderLoginRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/staff/login': typeof StaffLoginRoute
  '/service-areas': typeof ServiceAreasIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/facility/dashboard': typeof AuthenticatedFacilityDashboardRoute
  '/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
  '/provider/dashboard': typeof AuthenticatedProviderDashboardRoute
  '/provider/medicaid': typeof AuthenticatedProviderMedicaidRoute
  '/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/requests': typeof AuthenticatedRequestsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/integrations/hibambi/webhook': typeof ApiPublicIntegrationsHibambiWebhookRoute
  '/api/public/integrations/routegenie/webhook': typeof ApiPublicIntegrationsRoutegenieWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/changelog': typeof ChangelogRoute
  '/contact': typeof ContactRoute
  '/how-it-works': typeof HowItWorksRoute
  '/join-our-network': typeof JoinOurNetworkRoute
  '/mcp': typeof McpRoute
  '/membership': typeof MembershipRoute
  '/providers': typeof ProvidersRoute
  '/request-a-ride': typeof RequestARideRoute
  '/resources': typeof ResourcesRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/facility/login': typeof FacilityLoginRoute
  '/patient/login': typeof PatientLoginRoute
  '/provider/login': typeof ProviderLoginRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/staff/login': typeof StaffLoginRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/facility/dashboard': typeof AuthenticatedFacilityDashboardRoute
  '/_authenticated/patient/dashboard': typeof AuthenticatedPatientDashboardRoute
  '/_authenticated/provider/dashboard': typeof AuthenticatedProviderDashboardRoute
  '/_authenticated/provider/medicaid': typeof AuthenticatedProviderMedicaidRoute
  '/_authenticated/requests/$id': typeof AuthenticatedRequestsIdRoute
  '/_authenticated/requests/': typeof AuthenticatedRequestsIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/integrations/hibambi/webhook': typeof ApiPublicIntegrationsHibambiWebhookRoute
  '/api/public/integrations/routegenie/webhook': typeof ApiPublicIntegrationsRoutegenieWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/changelog'
    | '/contact'
    | '/how-it-works'
    | '/join-our-network'
    | '/mcp'
    | '/membership'
    | '/providers'
    | '/request-a-ride'
    | '/resources'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/training'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/dashboard'
    | '/checkout/return'
    | '/facility/login'
    | '/patient/login'
    | '/provider/login'
    | '/service-areas/$city'
    | '/staff/login'
    | '/service-areas/'
    | '/.mcp/invoke-tool/$tool'
    | '/facility/dashboard'
    | '/patient/dashboard'
    | '/provider/dashboard'
    | '/provider/medicaid'
    | '/requests/$id'
    | '/requests/'
    | '/api/public/payments/webhook'
    | '/api/public/integrations/hibambi/webhook'
    | '/api/public/integrations/routegenie/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/changelog'
    | '/contact'
    | '/how-it-works'
    | '/join-our-network'
    | '/mcp'
    | '/membership'
    | '/providers'
    | '/request-a-ride'
    | '/resources'
    | '/services'
    | '/sitemap.xml'
    | '/training'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin'
    | '/dashboard'
    | '/checkout/return'
    | '/facility/login'
    | '/patient/login'
    | '/provider/login'
    | '/service-areas/$city'
    | '/staff/login'
    | '/service-areas'
    | '/.mcp/invoke-tool/$tool'
    | '/facility/dashboard'
    | '/patient/dashboard'
    | '/provider/dashboard'
    | '/provider/medicaid'
    | '/requests/$id'
    | '/requests'
    | '/api/public/payments/webhook'
    | '/api/public/integrations/hibambi/webhook'
    | '/api/public/integrations/routegenie/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/changelog'
    | '/contact'
    | '/how-it-works'
    | '/join-our-network'
    | '/mcp'
    | '/membership'
    | '/providers'
    | '/request-a-ride'
    | '/resources'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/training'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/checkout/return'
    | '/facility/login'
    | '/patient/login'
    | '/provider/login'
    | '/service-areas/$city'
    | '/staff/login'
    | '/service-areas/'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/facility/dashboard'
    | '/_authenticated/patient/dashboard'
    | '/_authenticated/provider/dashboard'
    | '/_authenticated/provider/medicaid'
    | '/_authenticated/requests/$id'
    | '/_authenticated/requests/'
    | '/api/public/payments/webhook'
    | '/api/public/integrations/hibambi/webhook'
    | '/api/public/integrations/routegenie/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ChangelogRoute: typeof ChangelogRoute
  ContactRoute: typeof ContactRoute
  HowItWorksRoute: typeof HowItWorksRoute
  JoinOurNetworkRoute: typeof JoinOurNetworkRoute
  McpRoute: typeof McpRoute
  MembershipRoute: typeof MembershipRoute
  ProvidersRoute: typeof ProvidersRoute
  RequestARideRoute: typeof RequestARideRoute
  ResourcesRoute: typeof ResourcesRoute
  ServiceAreasRoute: typeof ServiceAreasRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrainingRoute: typeof TrainingRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  FacilityLoginRoute: typeof FacilityLoginRoute
  PatientLoginRoute: typeof PatientLoginRoute
  ProviderLoginRoute: typeof ProviderLoginRoute
  StaffLoginRoute: typeof StaffLoginRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicIntegrationsHibambiWebhookRoute: typeof ApiPublicIntegrationsHibambiWebhookRoute
  ApiPublicIntegrationsRoutegenieWebhookRoute: typeof ApiPublicIntegrationsRoutegenieWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-a-ride': {
      id: '/request-a-ride'
      path: '/request-a-ride'
      fullPath: '/request-a-ride'
      preLoaderRoute: typeof RequestARideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join-our-network': {
      id: '/join-our-network'
      path: '/join-our-network'
      fullPath: '/join-our-network'
      preLoaderRoute: typeof JoinOurNetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/staff/login': {
      id: '/staff/login'
      path: '/staff/login'
      fullPath: '/staff/login'
      preLoaderRoute: typeof StaffLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$city': {
      id: '/service-areas/$city'
      path: '/$city'
      fullPath: '/service-areas/$city'
      preLoaderRoute: typeof ServiceAreasCityRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/provider/login': {
      id: '/provider/login'
      path: '/provider/login'
      fullPath: '/provider/login'
      preLoaderRoute: typeof ProviderLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient/login': {
      id: '/patient/login'
      path: '/patient/login'
      fullPath: '/patient/login'
      preLoaderRoute: typeof PatientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facility/login': {
      id: '/facility/login'
      path: '/facility/login'
      fullPath: '/facility/login'
      preLoaderRoute: typeof FacilityLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/requests/': {
      id: '/_authenticated/requests/'
      path: '/requests'
      fullPath: '/requests/'
      preLoaderRoute: typeof AuthenticatedRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/requests/$id': {
      id: '/_authenticated/requests/$id'
      path: '/requests/$id'
      fullPath: '/requests/$id'
      preLoaderRoute: typeof AuthenticatedRequestsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/medicaid': {
      id: '/_authenticated/provider/medicaid'
      path: '/provider/medicaid'
      fullPath: '/provider/medicaid'
      preLoaderRoute: typeof AuthenticatedProviderMedicaidRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/provider/dashboard': {
      id: '/_authenticated/provider/dashboard'
      path: '/provider/dashboard'
      fullPath: '/provider/dashboard'
      preLoaderRoute: typeof AuthenticatedProviderDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/patient/dashboard': {
      id: '/_authenticated/patient/dashboard'
      path: '/patient/dashboard'
      fullPath: '/patient/dashboard'
      preLoaderRoute: typeof AuthenticatedPatientDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facility/dashboard': {
      id: '/_authenticated/facility/dashboard'
      path: '/facility/dashboard'
      fullPath: '/facility/dashboard'
      preLoaderRoute: typeof AuthenticatedFacilityDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/routegenie/webhook': {
      id: '/api/public/integrations/routegenie/webhook'
      path: '/api/public/integrations/routegenie/webhook'
      fullPath: '/api/public/integrations/routegenie/webhook'
      preLoaderRoute: typeof ApiPublicIntegrationsRoutegenieWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/hibambi/webhook': {
      id: '/api/public/integrations/hibambi/webhook'
      path: '/api/public/integrations/hibambi/webhook'
      fullPath: '/api/public/integrations/hibambi/webhook'
      preLoaderRoute: typeof ApiPublicIntegrationsHibambiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFacilityDashboardRoute: typeof AuthenticatedFacilityDashboardRoute
  AuthenticatedPatientDashboardRoute: typeof AuthenticatedPatientDashboardRoute
  AuthenticatedProviderDashboardRoute: typeof AuthenticatedProviderDashboardRoute
  AuthenticatedProviderMedicaidRoute: typeof AuthenticatedProviderMedicaidRoute
  AuthenticatedRequestsIdRoute: typeof AuthenticatedRequestsIdRoute
  AuthenticatedRequestsIndexRoute: typeof AuthenticatedRequestsIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFacilityDashboardRoute: AuthenticatedFacilityDashboardRoute,
  AuthenticatedPatientDashboardRoute: AuthenticatedPatientDashboardRoute,
  AuthenticatedProviderDashboardRoute: AuthenticatedProviderDashboardRoute,
  AuthenticatedProviderMedicaidRoute: AuthenticatedProviderMedicaidRoute,
  AuthenticatedRequestsIdRoute: AuthenticatedRequestsIdRoute,
  AuthenticatedRequestsIndexRoute: AuthenticatedRequestsIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ServiceAreasRouteChildren {
  ServiceAreasCityRoute: typeof ServiceAreasCityRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
}

const ServiceAreasRouteChildren: ServiceAreasRouteChildren = {
  ServiceAreasCityRoute: ServiceAreasCityRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
}

const ServiceAreasRouteWithChildren = ServiceAreasRoute._addFileChildren(
  ServiceAreasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ChangelogRoute: ChangelogRoute,
  ContactRoute: ContactRoute,
  HowItWorksRoute: HowItWorksRoute,
  JoinOurNetworkRoute: JoinOurNetworkRoute,
  McpRoute: McpRoute,
  MembershipRoute: MembershipRoute,
  ProvidersRoute: ProvidersRoute,
  RequestARideRoute: RequestARideRoute,
  ResourcesRoute: ResourcesRoute,
  ServiceAreasRoute: ServiceAreasRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrainingRoute: TrainingRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  FacilityLoginRoute: FacilityLoginRoute,
  PatientLoginRoute: PatientLoginRoute,
  ProviderLoginRoute: ProviderLoginRoute,
  StaffLoginRoute: StaffLoginRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicIntegrationsHibambiWebhookRoute:
    ApiPublicIntegrationsHibambiWebhookRoute,
  ApiPublicIntegrationsRoutegenieWebhookRoute:
    ApiPublicIntegrationsRoutegenieWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
