/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ServiceAreasRouteImport } from './routes/service-areas'
import { Route as RequestARideRouteImport } from './routes/request-a-ride'
import { Route as ProvidersRouteImport } from './routes/providers'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas.index'
import { Route as ServiceAreasCityRouteImport } from './routes/service-areas.$city'
import { Route as CheckoutReturnRouteImport } from './routes/checkout/return'
import { Route as AuthenticatedRequestsRouteImport } from './routes/_authenticated/requests'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicIntegrationsRoutegenieWebhookRouteImport } from './routes/api/public/integrations/routegenie.webhook'
import { Route as ApiPublicIntegrationsHibambiWebhookRouteImport } from './routes/api/public/integrations/hibambi.webhook'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasRoute = ServiceAreasRouteImport.update({
  id: '/service-areas',
  path: '/service-areas',
  getParentRoute: () => rootRouteImport,
} as any)
const RequestARideRoute = RequestARideRouteImport.update({
  id: '/request-a-ride',
  path: '/request-a-ride',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvidersRoute = ProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const ServiceAreasCityRoute = ServiceAreasCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => ServiceAreasRoute,
} as any)
const CheckoutReturnRoute = CheckoutReturnRouteImport.update({
  id: '/checkout/return',
  path: '/checkout/return',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRequestsRoute = AuthenticatedRequestsRouteImport.update({
  id: '/requests',
  path: '/requests',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsRoutegenieWebhookRoute =
  ApiPublicIntegrationsRoutegenieWebhookRouteImport.update({
    id: '/api/public/integrations/routegenie/webhook',
    path: '/api/public/integrations/routegenie/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicIntegrationsHibambiWebhookRoute =
  ApiPublicIntegrationsHibambiWebhookRouteImport.update({
    id: '/api/public/integrations/hibambi/webhook',
    path: '/api/public/integrations/hibambi/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/membership': typeof MembershipRoute
  '/providers': typeof ProvidersRoute
  '/request-a-ride': typeof RequestARideRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/integrations/hibambi/webhook': typeof ApiPublicIntegrationsHibambiWebhookRoute
  '/api/public/integrations/routegenie/webhook': typeof ApiPublicIntegrationsRoutegenieWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/membership': typeof MembershipRoute
  '/providers': typeof ProvidersRoute
  '/request-a-ride': typeof RequestARideRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/requests': typeof AuthenticatedRequestsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/service-areas': typeof ServiceAreasIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/integrations/hibambi/webhook': typeof ApiPublicIntegrationsHibambiWebhookRoute
  '/api/public/integrations/routegenie/webhook': typeof ApiPublicIntegrationsRoutegenieWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/membership': typeof MembershipRoute
  '/providers': typeof ProvidersRoute
  '/request-a-ride': typeof RequestARideRoute
  '/service-areas': typeof ServiceAreasRouteWithChildren
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/training': typeof TrainingRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/requests': typeof AuthenticatedRequestsRoute
  '/checkout/return': typeof CheckoutReturnRoute
  '/service-areas/$city': typeof ServiceAreasCityRoute
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/integrations/hibambi/webhook': typeof ApiPublicIntegrationsHibambiWebhookRoute
  '/api/public/integrations/routegenie/webhook': typeof ApiPublicIntegrationsRoutegenieWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/membership'
    | '/providers'
    | '/request-a-ride'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/training'
    | '/admin'
    | '/dashboard'
    | '/requests'
    | '/checkout/return'
    | '/service-areas/$city'
    | '/service-areas/'
    | '/api/public/payments/webhook'
    | '/api/public/integrations/hibambi/webhook'
    | '/api/public/integrations/routegenie/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/membership'
    | '/providers'
    | '/request-a-ride'
    | '/services'
    | '/sitemap.xml'
    | '/training'
    | '/admin'
    | '/dashboard'
    | '/requests'
    | '/checkout/return'
    | '/service-areas/$city'
    | '/service-areas'
    | '/api/public/payments/webhook'
    | '/api/public/integrations/hibambi/webhook'
    | '/api/public/integrations/routegenie/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/membership'
    | '/providers'
    | '/request-a-ride'
    | '/service-areas'
    | '/services'
    | '/sitemap.xml'
    | '/training'
    | '/_authenticated/admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/requests'
    | '/checkout/return'
    | '/service-areas/$city'
    | '/service-areas/'
    | '/api/public/payments/webhook'
    | '/api/public/integrations/hibambi/webhook'
    | '/api/public/integrations/routegenie/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  MembershipRoute: typeof MembershipRoute
  ProvidersRoute: typeof ProvidersRoute
  RequestARideRoute: typeof RequestARideRoute
  ServiceAreasRoute: typeof ServiceAreasRouteWithChildren
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TrainingRoute: typeof TrainingRoute
  CheckoutReturnRoute: typeof CheckoutReturnRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicIntegrationsHibambiWebhookRoute: typeof ApiPublicIntegrationsHibambiWebhookRoute
  ApiPublicIntegrationsRoutegenieWebhookRoute: typeof ApiPublicIntegrationsRoutegenieWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas': {
      id: '/service-areas'
      path: '/service-areas'
      fullPath: '/service-areas'
      preLoaderRoute: typeof ServiceAreasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/request-a-ride': {
      id: '/request-a-ride'
      path: '/request-a-ride'
      fullPath: '/request-a-ride'
      preLoaderRoute: typeof RequestARideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/providers': {
      id: '/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof ProvidersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/service-areas/$city': {
      id: '/service-areas/$city'
      path: '/$city'
      fullPath: '/service-areas/$city'
      preLoaderRoute: typeof ServiceAreasCityRouteImport
      parentRoute: typeof ServiceAreasRoute
    }
    '/checkout/return': {
      id: '/checkout/return'
      path: '/checkout/return'
      fullPath: '/checkout/return'
      preLoaderRoute: typeof CheckoutReturnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/requests': {
      id: '/_authenticated/requests'
      path: '/requests'
      fullPath: '/requests'
      preLoaderRoute: typeof AuthenticatedRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/routegenie/webhook': {
      id: '/api/public/integrations/routegenie/webhook'
      path: '/api/public/integrations/routegenie/webhook'
      fullPath: '/api/public/integrations/routegenie/webhook'
      preLoaderRoute: typeof ApiPublicIntegrationsRoutegenieWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/integrations/hibambi/webhook': {
      id: '/api/public/integrations/hibambi/webhook'
      path: '/api/public/integrations/hibambi/webhook'
      fullPath: '/api/public/integrations/hibambi/webhook'
      preLoaderRoute: typeof ApiPublicIntegrationsHibambiWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedRequestsRoute: typeof AuthenticatedRequestsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedRequestsRoute: AuthenticatedRequestsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ServiceAreasRouteChildren {
  ServiceAreasCityRoute: typeof ServiceAreasCityRoute
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
}

const ServiceAreasRouteChildren: ServiceAreasRouteChildren = {
  ServiceAreasCityRoute: ServiceAreasCityRoute,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
}

const ServiceAreasRouteWithChildren = ServiceAreasRoute._addFileChildren(
  ServiceAreasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  MembershipRoute: MembershipRoute,
  ProvidersRoute: ProvidersRoute,
  RequestARideRoute: RequestARideRoute,
  ServiceAreasRoute: ServiceAreasRouteWithChildren,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TrainingRoute: TrainingRoute,
  CheckoutReturnRoute: CheckoutReturnRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicIntegrationsHibambiWebhookRoute:
    ApiPublicIntegrationsHibambiWebhookRoute,
  ApiPublicIntegrationsRoutegenieWebhookRoute:
    ApiPublicIntegrationsRoutegenieWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
